### ISSUE TITLE
Full form of CAS

### ISSUE THREAD

**Issue by anshbansal** [matthiasn/talk-transcripts#11]
It would be great if you could add the full form of CAS. Not sure what that is.

**Comment by jafingerhut** [comment]
A quick response - it means "compare-and-swap".  One meaning for this is: an instruction in some processors that helps implement some operations that need to be atomic between multiple parallel threads, e.g. locking primitives. [1]

Rich sometimes in his talks seems to use it for a more general notion, e.g. _any_ mechanism that helps you implement something like a Clojure swap! operation on an atom, whether it is an instruction or something else.

Unless someone beats me to it, I can add a footnote with a link to the Wikipedia page to Rich's talk transcripts where he mentions CAS, and maybe also mention my guess that Rich sometimes uses it more generally than the processor instruction.

[1] https://en.wikipedia.org/wiki/Compare-and-swap

**Comment by matthiasn** [comment]
Thanks for the explanation. Closing this for now, feel free to open again if anything is unclear.
