### ISSUE TITLE
Value identity state talk from 2009

### ISSUE THREAD

**Issue by benjyz** [matthiasn/talk-transcripts#15]
http://www.infoq.com/presentations/Value-Identity-State-Rich-Hickey

**Comment by matthiasn** [comment]
Hi, what is the issue exactly?

**Comment by benjyz** [comment]
Hi, thanks for doing the transcripts of Hickey's talks. The only talk I found missing was the one mentioned above.

**Comment by matthiasn** [comment]
Cool, if you know anyone who wants to sponsor the transcription service, let me know. I'll be happy do do the proofreading in my free time.

**Comment by benjyz** [comment]
Ok, thanks again. I wasn't aware of how the transcripts were done. I found the list to be very useful for reference.

**Comment by matthiasn** [comment]
Sure, no problem. So far I paid for all of them, but that budget has come to an end.
