### ISSUE TITLE
Spec-ulation Keynote by Rich Hickey at Clojure/conj 2016

### ISSUE THREAD

**Issue by pdurbin** [matthiasn/talk-transcripts#28]
> "If you watch Rich Hickey's latest talk and can still defend SemVer or similar, then please write either a lot more or a lot less software." -- @brandonbloom at https://twitter.com/BrandonBloom/status/805168092108070912

I just watched "Spec-ulation Keynote" by Rich Hickey at https://www.youtube.com/watch?v=oyLBGkS5ICk which was the keynote from Clojure/conj 2016: http://2016.clojure-conj.org/rich-hickey-keynote/

The talk was great and I'm wondering if it would be possible to get a transcript of it. @candera has mentioned many times that the Cognicast podcast ( http://blog.cognitect.com/cognicast/ ) is professionally transcribed these days so I'm sort of wondering if that resource could be applied to this talk. @matthiasn has said "so I hired freelancers to transcribe some talks for me. I then did the proofreading and put the transcripts on GitHub" at http://matthiasnehlsen.com/blog/2014/10/15/talk-transcripts/ which is extremely generous! Thank you for all the transcripts so far!

**Comment by pdurbin** [comment]
Ah, I see that @puredanger is already listed at https://github.com/matthiasn/talk-transcripts/graphs/contributors which is awesome so I'm pinging him as well to see if he has any thoughts on this.

**Comment by candera** [comment]
Cognitect uses Pham Transcription Services for the Cognicast. We've been
happy with Tina's work.

http://phamtranscriptionservices.com/

**Comment by matthiasn** [comment]
Yup, Tina Pham does great work, she also did some of the transcripts on here. I'd be happy to facilitate more transcripts, but funding would have to come from some other source for the next round.

**Comment by pdurbin** [comment]
@matthiasn that makes sense. Did I do the right thing in opening this issue? I'm glad you're happy to help facilitate! If there's some other process to follow please let me know. Thanks.

@candera do you know if Rich plans to post his slides? That would actually go quite a long way. Transcripts are amazing but just having the slides to jog my memory would be very nice. Thanks.

**Comment by candera** [comment]
No idea what Rich's plans are in that regard, sorry.

**Comment by puredanger** [comment]
Rich typically does not post his slides as he prefers them to be viewed in the context of the talk.

**Comment by jafingerhut** [comment]
I have created a transcript of the Spec-ulation talk, available at the link below.  You are welcome to copy it into this repository, too, so more people can find it.  I can create a PR here if you are interested:

https://github.com/jafingerhut/jafingerhut.github.com/blob/master/transcripts/2016-dec-rich-hickey-spec-ulation.txt

**Comment by jafingerhut** [comment]
PR adding transcript of Rich's Spec-ulation talk created here: https://github.com/matthiasn/talk-transcripts/pull/37

**Comment by pdurbin** [comment]
@jafingerhut the pull request looks great! Thank you so much for creating that transcript!

**Comment by matthiasn** [comment]
Thank you, @jafingerhut
