### ISSUE TITLE
Interested in PRs with other Clojure-related transcripts?

### ISSUE THREAD

**Issue by jafingerhut** [matthiasn/talk-transcripts#35]
I have one I typed up here recently, which I don't mind creating a PR for if you are accepting them for this repo: https://github.com/jafingerhut/jafingerhut.github.com/blob/master/transcripts/2017-jun-stuart-halloway-repl-driven-development.txt

**Comment by matthiasn** [comment]
Hi Andy, that is great, thank you! Please do create a PR. Cheers

**Comment by jafingerhut** [comment]
Created PR here: https://github.com/matthiasn/talk-transcripts/pull/36
closing this issue
