### ISSUE TITLE
Do you have preference for video images vs. slide text in transcripts?

### ISSUE THREAD

**Issue by jafingerhut** [matthiasn/talk-transcripts#38]
For example, compare this, currently in this repository, which has still images of the video of the talk, to convey the contents of the speaker's slides: https://github.com/matthiasn/talk-transcripts/blob/master/Hickey_Rich/ValueOfValues.md

as compared to this version, which instead has text for the slide contents, which for this talk are almost purely text (plus one image of an astronaut next to the text on one slide late in the talk, which I did not attempt to convey): https://github.com/jafingerhut/jafingerhut.github.com/blob/master/transcripts/2012-rich-hickey-value-of-values.md

Of course, one need not have only one or the other of these, but I thought I would ask in case anyone would prefer the version with text for slide contents instead of images.

**Comment by matthiasn** [comment]
I'm undecided at this point. The actual slides in my opinion look a little better, whereas plain text is searchable. Maybe anyone else has a stronger opinion?

One thing that would be sweet in either case is linking to the specific time of a slide in the youtube video.

**Comment by c00kiemon5ter** [comment]
+1 for linking to time
+1 for text when the slide is only or mostly text and the image does not really add any value
+1 for including images when it really makes sense

for example see #41 
The images displaying the dependency links from the Spec-ulation slides do add value.

**Comment by jafingerhut** [comment]
As another example, here is the current transcript for one of Rich's core.async talks: https://github.com/matthiasn/talk-transcripts/blob/master/Hickey_Rich/CoreAsync.md

Here is a version with mostly text for slides (keeping the images for the figure-heavy slides): https://github.com/jafingerhut/talk-transcripts/blob/update-core-async-transcript/Hickey_Rich/CoreAsync.md

It is certainly possible to add this to the repo in a way such that both are available, side by side, and let people pick the one they want, e.g. CoreAsync.md and CoreAsync-mostly-text.md (or some better name), with a link in the talk list to each one.

**Comment by c00kiemon5ter** [comment]
Accessibility-wise I would prefer [the later](https://github.com/jafingerhut/talk-transcripts/blob/update-core-async-transcript/Hickey_Rich/CoreAsync.md) with not-every-slide-as-an-image, as I described above. Regardless of the choice, thanks for all this! Keep up the good work.

Cheers 🍺 🍺

**Comment by jafingerhut** [comment]
I created a proposed PR that adds a CoreAsync-mostly-text.md variant of the transcript.

**Comment by jafingerhut** [comment]
Closing this issue, as I think the answers given are sufficient to motivate me to create text-only versions for slides that have no images (but still use screen capture images when there are figures that are time consuming or much less pretty when you attempt to render them in ASCII art).
