### ISSUE TITLE
Consider adding transcript of this Rich Hickey interview

### ISSUE THREAD

**Issue by jafingerhut** [matthiasn/talk-transcripts#70]
Matthias, I hope you do not mind me creating an issue here for this.  It is mainly a reminder for me to look into adding this -- I am not intending to ask you to do it for me.  Issues on this repository are a convenient place to store such reminder, if that is OK.

jumar [9:10 AM]
This is a fantastic reading: https://gist.github.com/jumarko/d672dbe746b3c10ee2690b2e17624de3
There are probably many things that I don't understand, but to mention one:
> protocols support direct implementation composition, which, in my opinion, is far preferable to inheritance
I'm not sure what exactly "protocols support directly implementation composition" really means here. 
Can anyone elaborate on that a bit more? (edited)

tbaldridge [9:16 AM]
@jumar it means that given a protocol IFoo you can extend it to any type, new or previously existing. Unlike interfaces which require you to inherit from the interface at compile time. So assume I have ICounted as a protocol, I can just easily add it to a new type as I can to go and do this

```(extend-protocol ICounted
  String
  (count [this]
    (.getLength this)))```

String is a built-in type that I can't modify, but protocols allow me to extend the protocol to this type. This really helps with things like the "expression problem"
Good overview of that here: https://eli.thegreenplace.net/2016/the-expression-problem-and-its-solutions

jumar [9:19 AM]
Ah, okay, so the "composition" here means adding new capability to the existing data type. I was thinking about `extend-protocol` as related to the first Rich's claim, that is "Protocols support direct connections of datatypes to protocols, without any inheritance" and was somewhat puzzled by the "implementation composition" words.

**Comment by matthiasn** [comment]
Hi Andy, sure, that's totally fine. I want to spend some time this weekend reading and listening to the talks you added, thanks a lot for those.

**Comment by jafingerhut** [comment]
And thanks to you for all the ones you created and made available first!  I'd much rather add to your pile than start a separate one.

**Comment by jafingerhut** [comment]
Added a PR with this interview here: https://github.com/matthiasn/talk-transcripts/pull/71

I will leave this issue open for a bit longer, in case I decide to add some notes/discussion from the comment above to the article, for readers looking for more info.

**Comment by lread** [comment]
Can probably close this one as done @jafingerhut?

**Comment by jafingerhut** [comment]
Definitely.  Thanks for pointing it out.
