### ISSUE TITLE
Stuart Halloway: Debugging with the Scientific Method

### ISSUE THREAD

**Issue by vvvvalvalval** [matthiasn/talk-transcripts#72]
https://github.com/stuarthalloway/presentations/wiki/Debugging-with-the-Scientific-Method

I'm starting to write the transcript, this issue is just to coordinate with other potential contributors.

**Comment by jafingerhut** [comment]
Wooh!  Go for it.

**Comment by matthiasn** [comment]
Thanks again, forgot to close after merging the PR
