### ISSUE TITLE
Consider adding Rich Hickey Talk: "Clojure Concurrency"

### ISSUE THREAD

**Issue by juliangamble** [matthiasn/talk-transcripts#89]
Please consider adding this Rich Hickey talk: "Clojure Concurrency"

https://www.youtube.com/watch?v=dGVqrGmwOAw

**Comment by jafingerhut** [comment]
I am in progress on transcribing that talk now.  Probably have something in a few days.  If I _don't_  create a PR by the end of Nov-2019, feel free to go for it, as I have dropped the ball somehow on it.

**Comment by jafingerhut** [comment]
PR here: https://github.com/matthiasn/talk-transcripts/pull/90

**Comment by juliangamble** [comment]
Bam! You turned that around quickly! Very impressive.

**Comment by jafingerhut** [comment]
Please close this issue, as the new transcript has been merged in.  I would, but do not have permission to close issues here.  Thanks.
